### ISSUE TITLE
Outdated WordPress Plugins

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-deploy#63]
There were several WordPress Plugins that were out of date:
- [x] /q-and-a/
- [x] w3-total-cache/
- [x] wordpress-seo/
- [x] wp-rss-multi-importer/

**Comment by dano-reisys** [comment]
- We are not using `q-and-a` anymore
- We've upgraded `w3-total-cache`: https://github.com/GSA/datagov-wp-boilerplate/blob/no-map/composer.json#L44
- Using the latest version of `wordpress-seo`: https://github.com/GSA/datagov-wp-boilerplate/blob/no-map/composer.json#L47
- Using the `rss-post-importer` instead of `wp-rss-multi-importer`: https://github.com/GSA/datagov-wp-boilerplate/blob/no-map/composer.json#L48
